### ISSUE TITLE
Have an introduction dialog when people come to the genmapper for the first time

### ISSUE THREAD

**Issue by holybiber** [4training/GenMapper#10]
This dialog should have a box "don't show this again" which is ticked by default -> set a cookie so that next time this dialog won't be shown again.
Contents (roughly):

Welcome to the genmapper! You find an introduction to this [here].
Privacy is very important for us and we're not storing any of your data on our server. More specifically, this app is running solely in your browser and no information of it is sent anywhere else. Please export any church tree that you're creating and save it on your computer to make sure it doesn't get losted.
Additionally the data is stored in the local storage of your browser and you can continue when you come back. Caution: When you're deleting cookies / temporary data in your browser, this data gets deleted! Also you won't see your data when you use a different device.
```

```

**Comment by Krutsch** [comment]
Done
