### ISSUE TITLE
Remove the "Please login" screen at beginning

### ISSUE THREAD

**Issue by holybiber** [4training/GenMapper#4]
Currently let's not implement the login to avoid saving any sensitive data on the server. So this shouldn't be shown at all at the beginning (directly "continue without saving")

**Comment by Krutsch** [comment]
Should it show this continue without saving or should it redirect to the canvas?

**Comment by holybiber** [comment]
It should directly redirect to the canvas (and show the dialog from #10)

**Comment by Krutsch** [comment]
Done
