### ISSUE TITLE
Add hints / warning on unsaved changes

### ISSUE THREAD

**Issue by holybiber** [4training/GenMapper#5]
Our goal is that people edit their generational map and then export and save it on their computer.

First for clarification: It seems like the genmapper is storing the work in the browser - what and how exactly?

Then let's explain that better to the user and probably introduce a warning when a user is about to leave the page without having exported his tree. (via event listener for beforeunload)

**Comment by Krutsch** [comment]
I noticed that there is a login functionality. Is the data not saved while being logged in? 
At the start of the app, the user has two possible actions: **login** or **continue without save**. Even though the _continue without save_ will actually save the tree under `localStorage['offline-nodes-v2-churchCircles']`, I think adding another warning promt is a bit too much. Additionally those prompts have a bad reputition and a bad UX.
![image](https://user-images.githubusercontent.com/45216083/109201670-035c9480-779a-11eb-8541-5803b8537916.png)

What do you think?

**Comment by holybiber** [comment]
The client brings this login functionality, but we don't have the server running and currently no plans to enable that. We only have the continue without save feature. So with you saying that I opened #10 as maybe a better idea. What do you think?

**Comment by holybiber** [comment]
Actually we may add another box "Warn me when I'm about to leave with unexported changes" to the #10 dialog which would not be ticked per default. Some people may appreciate that, what do you think? Wouldn't be top priority though.

**Comment by Krutsch** [comment]
From what I see, the tree is being saved already. In this case we do not need a change. Does this not work correctly? 

Or would you like to have a toggle to turn this on/off? If yes, what should be the default setting?
Cannot think of a reason why it should be a toggle though.

**Comment by holybiber** [comment]
I meant the "Export CSV" feature and warn when someone is closing the window without a deliberate export before. Having the tree always being saved in the browser is nice and convenient but you can't really rely on that, we'd want people to really responsibility and export what they're doing, that's why such an addition came into my mind.

**Comment by Krutsch** [comment]
done
